-- +goose Up

-- 项目表
CREATE TABLE project (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    summary      TEXT,
    cover        VARCHAR(255),
    content      TEXT         NOT NULL DEFAULT '',
    status       VARCHAR(32)  NOT NULL DEFAULT '进行中',
    short_url    VARCHAR(255) NOT NULL,
    author_id    BIGINT       NOT NULL,
    is_published BOOLEAN      DEFAULT false,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ  DEFAULT now(),
    deleted_at   TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_project_short_url ON project (short_url) WHERE deleted_at IS NULL;
CREATE INDEX idx_project_deleted_at ON project (deleted_at);

-- +goose Down

DROP INDEX IF EXISTS idx_project_deleted_at;
DROP INDEX IF EXISTS idx_project_short_url;
DROP TABLE IF EXISTS project;
